server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${AWS_RDS_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always # 추후 수정예정
      continue-on-error: true
      data-locations: classpath:sql/data.sql
