spring:
  config:
    activate:
      on-profile: security

jwt:
  hmac512:
    secret-key: ${SECRET_KEY}

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}