spring:
  config:
    activate:
      on-profile: security

jwt:
  hmac512:
    secret-key: 123456789

oauth2:
  kakao:
    client-id: be8542abac947a6d7c8f0302c7a488be
    client-secret: ehEunzUMzlEKCFYLTyxavcFNLA76SGfx
  naver:
    client-id: vkJAvYpNJR4avwLpsOEZ
    client-secret: htb_llRHOx