#!/bin/bash
#
#https://wiki.debian.org/LSBInitScripts
### BEGIN INIT INFO
# Provides:          restdocker
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start restdocker
# Description:       Start the restdocker
### END INIT INFO

start()
{
  logger -t restdocker "Starting restdocker Service"
  /opt/bin/scripts/service/start-restdocker-service.sh
}

stop()
{
  logger -t restdocker "Stop restdocker Service"
  /opt/bin/scripts/service/stop-restdocker-service.sh
}

case $1 in
    start|stop) $1;;
    restart) stop; start;;
    *) echo "Usage : $0 <start|stop|restart>"; exit 1;;
esac

exit 0